import Head from 'next/head';
import styles from '@/styles/Home.module.css'
import { createClient } from 'contentful'


export default function Home({data}) {
  console.log(data[0].fields)
  return (
    <>
      <Head>
        <title>Contentful Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h4>Importing data from Contentful!!</h4>
        {data?.map(item =>
          <div key={item.fields.id} className='card'>
            <p>name: {item.fields.name}</p>
            <p>age: {item.fields.age}</p>
            <img src={item.fields.image.fields.file.url} alt={item.fields.image.fields.title}/>
          </div>
        )}
      </main>
    </>
  )
}

export async function getStaticProps(){
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });
  const res = await client.getEntries({ content_type: 'practiceData'});
  return{
    props: {
      data: res.items
    }
  }
}
